on:
  push:
    branches:
      - main
name: Deploy to the Production Environment on main Branch
jobs:
  web-deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Use Production env
      run: cp env.production .env
        
    - name: Install vendors
      run: |
          composer install --prefer-dist --no-dev --optimize-autoloader
          rm -rf node_modules package-lock.json
          npm install
          npm run build
          npm ci --no-optional
          php artisan route:clear
          php artisan view:clear
          php artisan route:cache
          php artisan view:cache

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: iad1-shared-e1-05.dreamhost.com
        username: dh_rcdg7r
        password: Ovindu@012
        timeout_minutes : 1
        max_attempts : 3
        server-dir: system.sisintravels.com/

    - name: Check website status
      run: curl -I https://system.sisintravels.com
